name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - macos-14
        cosign:
          - true
          - false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Cosign
        if: ${{ matrix.cosign }}
        uses: sigstore/cosign-installer@3454372f43399081ed03b604cb2d021dabca52bb # ratchet:sigstore/cosign-installer@v3

      - name: Get Cosign version
        if: ${{ matrix.cosign }}
        run: cosign version

      - name: Plugin test
        uses: asdf-vm/actions/plugin-test@1902764435ca0dd2f3388eea723a4f92a4eb8302 # ratchet:asdf-vm/actions/plugin-test@v3
        with:
          command: tenv version
