name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4

      - uses: asdf-vm/actions/install@1902764435ca0dd2f3388eea723a4f92a4eb8302 # ratchet:asdf-vm/actions/install@v3
        with:
          asdf_branch: v0.15.0

      - run: scripts/lint.sh

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4

      - name: Check workflow files
        uses: docker://index.docker.io/rhysd/actionlint@sha256:d84eca815fc24f72546ec1f2f416d9500ad3349ce7db098cf7a52256f5fd4384 # ratchet:docker://rhysd/actionlint:1.6.27
        with:
          args: -color
