name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@c2a5a2bd6a758a0937f1ddb1e8950609867ed15c # ratchet:GoogleCloudPlatform/release-please-action@v4
        with:
          release-type: simple
